#!/usr/bin/env bash
# Configure Nginx to listen to port 80

rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart

