#!/usr/bin/env bash
# Script: 1-show_attached_IPs
# Description: Displays all active IPv4 IPs on the machine.

# Use ifconfig to get network interface information and filter for IPv4 addresses
ifconfig | grep -oP 'inet \K[\d.]+'
