#!/usr/bin/env bash
# Configures Nginx to run as nginx user and listen on port 8080
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
